### ISSUE TITLE
Authors graph for LKML

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#14]
What is the complete authors graph for LKML. The graph plotting conventions are same as those outlined in issue #13. The following are the relevant questions on this graph.
1. Are there any disconnected components in this graph? If so, plot them separately.
2. What are the communities detected by the igraph/networkx? Plotting these using networkx/graphviz would be useful.

**Comment by prasadtalasila** [comment]
How many weakly connected components exist? List the authors who are part of these weakly connected components.

**Comment by achyudh** [comment]
- Regarding community detection, please check commit d462d1b. 
- Plotting these communities without overlaps in a discernible manner would be an issue due to the 1000+ number of nodes in some communities. 
- The issue of strongly and weakly connected components has already been addressed. The entire graph is a weakly connected component with a single dominant strongly connected component and the rest of them being stray nodes.
