### ISSUE TITLE
Author version of width-height table

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/MailingListParser#16]
A width-height table for author graphs. The conventions of width-height table used in issue #9 can be used.

These graphs tell us the basic conversation structure. Especially, how many 2-way, 3-way, 4-way etc. conversations happen in a discussion thread.

The format of the table can be as follows.
![image](https://cloud.githubusercontent.com/assets/9206466/12780362/7f4382de-ca93-11e5-8f84-ea872bebd39d.png)

**Comment by achyudh** [comment]
Commit fceeb1e addresses this issue. Please find the generated table in the "data/graphs/csv" folder.

**Comment by prasadtalasila** [comment]
The meaning of the two tables in wh_table_authors.csv is not completely clear. It would be good to have the table produced in the specified format.

**Comment by achyudh** [comment]
With the given format, since a CSV file does not have any formatting, it gets very clumsy. Further, the total and the subtotals of both new authors and all authors cannot be captured. Hence I created separate tables for new authors and the total number of authors. The first table shows the number of threads with a **total** of 'i' authors at a height 'h' and the second, No. of threads with a 'i' **new** authors at a height 'h'.

**Comment by achyudh** [comment]
Please check commit 7d08f85. The reformatted table is in the "data/graphs/csv" folder.
