### ISSUE TITLE
Name of generate_author_ranking changed to get

### ISSUE THREAD

**Issue by yashpungaliya** [prasadtalasila/MailingListParser#98]
Above changes not reflected in driver files and some input code files

**Comment by yashpungaliya** [comment]
Fixed in #99

**Comment by achyudh** [comment]
@yashpungaliya This is not the correct solution to this problem. When the project was reorganized to be modular `generate_author_ranking` was changed to` author.ranking.get`. Now it would be `author.ranking.generate_author_ranking` which is out of place and in-elegant. You need to uniformly change everything to author.ranking.get, rather than the opposite which you have just done. 

Also please allow @prasadtalasila some time to review the code before merging. The change you made needs to be reverted back now,

**Comment by achyudh** [comment]
Fixed in Development #103
